name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda Path
      run: echo $CONDA/bin >> $GITHUB_PATH

    - name: Cache Conda env
      uses: actions/cache@v3
      with:
        path: /usr/share/miniconda/envs/base
        # The cache key is based on the hash of your environment file
        key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
        restore-keys: |
          conda-${{ runner.os }}-

    - name: Install dependencies
      run: |
        # Update env and force install dev tools into the 'base' env
        conda env update --file environment.yml --name base

    - name: Check Environment
      run: |
        conda run -n base python --version
        conda run -n base conda info

    - name: Check formatting with Black
      run: conda run -n base black --check .

    - name: Lint with flake8
      run: |
        conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: conda run -n base pytest --exitfirst || echo "No tests found yet"
